[images]
  remote_images = ["https://*.unsplash.com", "https://*.pexels.com", "https://*.picsum.photos", "https://*.*.amazonaws.com", "https://*.cloudinary.com"]

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_USE_NETLIFY_EDGE = "true"

[dev]
  command = "next dev -H 0.0.0.0"
  port = 3000
  targetPort = 3000

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
  force = false
  conditions = {Role = ["anonymous"]}

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Force https
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true
